<?xml version="1.0" standalone="yes"?>
<!DOCTYPE SITES
[
    <!ELEMENT SITES (VERSION, SITE+)>
    <!ELEMENT VERSION (#PCDATA)>
    <!ELEMENT SITE (ID, NAME, MAXADDR, MAXALIASES, MAXQUOTA, TYPE, DOMAINS?, USERS?, ALIASES?)>
    <!ELEMENT DOMAINS (DOMAIN*)>
    <!ELEMENT DOMAIN (#PCDATA)>

    <!ELEMENT USERS (USER*)>
    <!ELEMENT USER (ID, NAME, ROA, ROC, QUOTA, TYPE)>

    <!ELEMENT ALIASES (ALIAS*)>
    <!ELEMENT ALIAS (LEFTPART, RIGHTPART)>
    
    <!ELEMENT ID (#PCDATA)>
    <!ELEMENT NAME (#PCDATA)>
    <!ELEMENT MAXADDR (#PCDATA)>
    <!ELEMENT MAXALIASES (#PCDATA)>
    <!ELEMENT MAXQUOTA (#PCDATA)>
    <!ELEMENT TYPE (#PCDATA)>

    <!ELEMENT ROA (#PCDATA)>
    <!ELEMENT ROC (#PCDATA)>
    <!ELEMENT QUOTA (#PCDATA)>

    <!ELEMENT LEFTPART (#PCDATA)>
    <!ELEMENT RIGHTPART (#PCDATA)>
]
>
<SITES>
<VERSION>1</VERSION>
<SITE>
	<ID>60</ID>
	<NAME>abtauchen</NAME>
	<MAXADDR>1</MAXADDR>
	<MAXALIASES>1</MAXALIASES>
	<MAXQUOTA>10240</MAXQUOTA>
	<TYPE>p</TYPE>
	<DOMAINS>
		<DOMAIN>abtauchen.at</DOMAIN>
		<DOMAIN>abtauchen.com</DOMAIN>
		<DOMAIN>abtauchen.net</DOMAIN>
	</DOMAINS>
	<USERS>
		<USER>
			<ID>83</ID>
			<NAME>info</NAME>
			<ROA>y</ROA>
			<ROC>n</ROC>
			<QUOTA>10240</QUOTA>
			<TYPE>p</TYPE>
		</USER>
	</USERS>
	<ALIASES>
		<ALIAS>
			<LEFTPART>*</LEFTPART>
			<RIGHTPART>info</RIGHTPART>
		</ALIAS>
	</ALIASES>
</SITE>
</SITES>